export const config = {
  openAiApiKey: process.env.OPENAI_API_KEY ?? "",
  modelTranscribe: process.env.MODEL_TRANSCRIBE ?? "gpt-4o-mini-transcribe",
  modelMonitor: process.env.MODEL_MONITOR ?? "gpt-4.1-mini",
  modelPersonaSynthesis: process.env.MODEL_PERSONA_SYNTHESIS ?? "gpt-4.1",
  modelShadowBoard: process.env.MODEL_SHADOW_BOARD ?? "gpt-4.1",
  modelTextToSpeech: process.env.MODEL_TEXT_TO_SPEECH ?? "gpt-4o-mini-tts-2025-12-15",
  boardAgentVoice: process.env.BOARD_AGENT_VOICE ?? "cedar",
  persistTranscripts: (process.env.PERSIST_TRANSCRIPTS ?? "true") === "true",
  persistRawAudio: (process.env.PERSIST_RAW_AUDIO ?? "false") === "true",
  enableRedaction: (process.env.ENABLE_REDACTION ?? "true") === "true",
  traceExportEnabled: (process.env.TRACE_EXPORT_ENABLED ?? "true") === "true",
  traceProject: process.env.OPENAI_TRACING_PROJECT ?? "morgan-virtual-board",
  traceOrganization: process.env.OPENAI_TRACING_ORGANIZATION ?? "",
  traceEndpoint: process.env.OPENAI_TRACING_ENDPOINT ?? "",
};
